# Generated by Django 3.1.5 on 2022-06-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member_table',
            fields=[
                ('mb_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mb_pw', models.CharField(max_length=20)),
                ('mb_name', models.CharField(max_length=20)),
                ('mb_address', models.CharField(max_length=50)),
                ('mb_phone', models.CharField(max_length=20)),
                ('mb_email', models.CharField(max_length=50)),
            ],
        ),
    ]
