# Generated by Django 3.1.5 on 2022-06-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='member_table',
        ),
    ]
