# Generated by Django 3.1.5 on 2022-08-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20220803_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_contact',
            name='text',
            field=models.TextField(),
        ),
    ]
